name: C/C++ AppImage

on:
  workflow_dispatch:

jobs:
  build-appimage:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install curl
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.9.9
        
      - name: Prepare compiler env
        run: |
          echo "::set-env name=CC::gcc-8"
          echo "::set-env name=CXX::g++-8"

      - name: Configure
        run: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .

      - name: Build
        run: ninja klogg-io

      - name: Install
        run: DESTDIR=AppDir ninja install 

      - name: Bundle Qt
        run: |
          wget -c -q "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/bin/klogg-io -qmake=$Qt5_Dir/bin/qmake
      
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|klogg-io|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml

      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'